export const courses = {
  title: "Our Courses",
  description:
    "Learn the latest technologies and build real-world projects with our courses.",
  LinkMessage: "View All Courses",
  Link: "/courses",
  TotalCourses: "10+",
  TotalStudents: "10K+",
  // course categories
  categories: [
    { name: "Web Development", link: "/web-development" },
    { name: "Mobile App Development", link: "/mobile-app-development" },
    { name: "Data Science", link: "/data-science" },
    { name: "Machine Learning", link: "/machine-learning" },
    { name: "Artificial Intelligence", link: "/artificial-intelligence" },
    { name: "Cloud Computing", link: "/cloud-computing" },
    { name: "Cyber Security", link: "/cyber-security" },
    { name: "Digital Marketing", link: "/digital-marketing" },
  ],

  // popular courses
  popularCourses: [
    {
      id: 1,
      title: "Data Science and Analytics",
      description:
        "Learn web development with HTML, CSS, JavaScript, React, Node.js, and more.",
      image: "/images/homepageImg/D&A_resized.png",
      link: "/web-development",
      old_price: 12000,
      new_price: 6000,
      bookNow:
        "https://docs.google.com/forms/d/e/1FAIpQLSeugzwzo8H2bHspG_hu77o4c_C3_Uwd_CuT7MpDnnJhYFx2kQ/viewform",
    },
    {
      id: 2,
      title: "Mastering Data Analysis",
      description:
        "Learn web development with HTML, CSS, JavaScript, React, Node.js, and more.",
      image: "/images/homepageImg/DA.png",
      link: "/web-development",
      old_price: 8000,
      new_price: 4000,
      bookNow:
        "https://docs.google.com/forms/d/e/1FAIpQLSdSNfuMyNobXs_5Pgp_Qk8LXgPR9w6oMS5OAf7ublXPFacUgA/viewform",
    },
    {
      id: 3,
      title: "Data Analysis with Python",
      description:
        "Learn web development with HTML, CSS, JavaScript, React, Node.js, and more.",
      image: "/images/homepageImg/DAP.png",
      link: "/web-development",
      old_price: 3000,
      new_price: 2000,
      bookNow:
        "https://docs.google.com/forms/d/e/1FAIpQLScChLY7jtDzyf9pvQnfXRA3XQwiTa1w9JMGrvAj1FwKaZ3gzQ/viewform",
    },
    {
      id: 4,
      title: "Mysql for Data Analysis",
      description:
        "Learn web development with HTML, CSS, JavaScript, React, Node.js, and more.",
      image: "/images/homepageImg/mysql.png",
      link: "/web-development",
      old_price: 3000,
      new_price: 2000,
      bookNow:
        "https://docs.google.com/forms/d/e/1FAIpQLSfCdTDsusJwTB9wl1A0IP-Im10oFm9h9fsNFYO7jliHfPgK-A/viewform?usp=send_form",
    },
    {
      id: 5,
      title: "Data Mastery with PowerBi",
      description:
        "Learn web development with HTML, CSS, JavaScript, React, Node.js, and more.",
      image: "/images/homepageImg/powerbi.png",
      link: "/web-development",
      old_price: 3000,
      new_price: 2000,
      bookNow:
        "https://docs.google.com/forms/d/e/1FAIpQLScQCw3WmzLjt0ct_dimgh8JkF1N8ZF_oDV77QRpeNY4bk98cA/viewform",
    },
    {
      id: 6,
      title: "Introduction to Natural Language Processing (NLP)",
      description:
        "Learn web development with HTML, CSS, JavaScript, React, Node.js, and more.",
      image: "/images/homepageImg/nlp.png",
      link: "/web-development",
      old_price: 5000,
      new_price: 3000,
      bookNow:
        "https://docs.google.com/forms/d/e/1FAIpQLSc8gvaMwV8V5nGs4aZymFHMyG-AJidHrMc8sLJRareDA0vX_w/viewform",
    },
  ],
};

export const courseData = [
  {
    id: "1",
    title: "Data Science and Analytics",
    instructor: "Md. Asif Mredha",
    instructorDetails: [
      "Managing Director, Kryzotech",
      "Machine Learning Trainer, Hamdard University Bangladesh",
      "Former Data Scientist, Nighthawk",
      "Former Data Science Trainer, Microland IT Institute",
      'Formulated the course outline for the "Big Data, Data Analytics, and Data Science" for SEIP',
    ],
    modules: [
      {
        id: 1,
        title: "Introduction to Data Science",
        topics: [
          "Overview of Data Science",
          "Roadmap to Becoming a Data Scientist",
          "Importance of Data Science in Industry",
          "Real-world Applications of Data Science",
        ],
      },
      {
        id: 2,
        title: "Programming Language (Python)",
        topics: [
          "Introduction to Python for Data Science",
          "Setup and Installation:",
          "·	Installing Python and IDEs (e.g., PyCharm, VS Code, Jupyter Notebook).",
          "Basic Syntax",
          "·	Print Function, Variables, and Input Handling",
          "Data Types and Casting",
          "·	Overview of Python Data Types",
          "·	Casting between data types",
          "Operators",
          "·	Arithmetic, Assignment, Comparison, Logical, Identify, and Membership operators",
          "Statements",
          "·	Comments, Pass, Break, Continue, and Switch-case Implementations.",
          "Problem Solving",
          "·	Writing simple Python programs to solve basic problems",
          "Python Control Flow and Data Structures",
          "Control Flow:",
          "·	If-Else Statements and Nested Loops",
          "·	For and While Loops with practical examples",
          "Data Structures",
          "·	Overview of Lists, Tuples, Dictionaries, and Arrays",
          "·	Practical use cases for each data structure",
          "Functions in Python:",
          "·	Defining Functions, Parameters, and Return Statements",
          "·	Lambda Functions and their applications.",
          "Basics of Object-Oriented Programming (OOP):",
          "·	Introduction to Classes and Objects",
          "·	Attributes and Methods",
          "·	Constructors (__init__ method)",
          "·	Inheritance ",
          "·	Encapsulation and Abstraction",
          "·	Polymorphism",
          "Exception Handling in Python:",
          "·	Try-Except Block",
          "·	Finally Block",
          "·	Raising Exceptions",
          "File Handling in Python:",
          "·	Reading Text Files",
          "·	Writing & Appending to Text Files",
          "·	Delete file & folder",
          "Project:",
          "·	Develop a small project using Python",
        ],
      },
      {
        id: 3,
        title: "Unlocking Numerical Computing using Numpy",
        topics: [
          "NumPy Basics:",
          "·	Introduction to Jupyter Notebook",
          "·	Creating and Manipulating Arrays",
          "·	Slicing, Dicing, and Reshaping Arrays",
          "Mathematical Operations:",
          "·	Basic Arithmetic, Random Value Generation",
          "·	Min/Max/Mean Functions, Joining and Splitting Arrays",
        ],
      },
      {
        id: 4,
        title: "Data Manipulation with Pandas",
        topics: [
          "Introduction to Pandas:",
          "·	Importing and Exporting Datasets",
          "·	Handling Missing Data",
          "DataFrame Operations:",
          "·	Dropping, Grouping, and Sorting Data",
          "·	Filtering Data, Creating New Columns",
          "Project: Exploratory Data Analysis (EDA) on a Real Dataset Using Pandas",
        ],
      },
      {
        id: 5,
        title: "Data Visualization with Matplotlib",
        topics: [
          "Basic Plotting:",
          "·	Line, Scatter, and Bar Plots",
          "·	Customizing Plots: Labels, Grids, Legends",
          "Advanced Visualizations:",
          "·	Subplots, Histograms, Pie Charts",
          "·	Plot Styles and Aesthetics",
          "Project: Visualizing Trends in Data Using Matplotlib",
        ],
      },
      {
        id: 6,
        title: "Data Visualization with Seaborn",
        topics: [
          "Introduction to Seaborn:",
          "·	Relational and Categorical Plots (Scatter, Line, Bar, Box, etc.)",
          "Distribution and Aesthetics:",
          "·	Histograms, KDE Plots, and Violin Plots",
          "·	Customizing Seaborn Colors and Plot Grids",
          "Project: Create Detailed Plots to Explore Data Patterns",
        ],
      },
      {
        id: 7,
        title: "Statistics",
        topics: [
          "Descriptive Statistics",
          "Probability Theory",
          "Hypothesis Testing",
          "Statistical Inference",
          "Correlation and Regression Analysis",
          "Forecasting: Time Series Analysis",
        ],
      },
      {
        id: 8,
        title: "Machine Learning",
        topics: [
          "Data Preprocessing and Feature Engineering",
          "Data Cleaning Techniques:",
          "·	Handling Missing Data, Encoding Categorical Variables",
          "Feature Engineering:",
          "·	Feature Selection, Scaling, and Transformation",
          "·	Data Mining Techniques, Splitting Data",
          "Handling Imbalanced Datasets:",
          "·	Undersampling, Oversampling and SMOTE",
          "Overview of Machine Learning:",
          "·	Definition and Key Concepts: Training, Validation, Testing",
          "·	Types: Supervised, Unsupervised, Reinforcement Learning",
          "·	Real-World Applications",
          "Supervised and Unsupervised Learning",
          "Supervised Learning: Algorithms like Linear Regression, Logistic Regression, Decision Trees, Random Forests, KNN, Naive Bayes, SVM and so on",
          "Examples: Bitcoin price prediction, Predicting Sales, Credit Card Default, Customer churn and so on.",
          "Unsupervised Learning: ",
          "Clustering Techniques:",
          "·	K-means, Hierarchical Clustering",
          "Market Basket Analysis:",
          "·	Association Rule Learning",
          "Dimensionality Reduction:",
          "·	Principal Component Analysis (PCA)",
          "·	Dimensionality Test using PCA",
          "Project: Customer segmentation, Market basket analysis ",
          "Performance Evaluation Metrics:",
          "·	Regression: MAE, MSE, RMSE, R²",
          "·	Classification: Accuracy, Precision, Recall, F1-Score, Confusion Matrix",
          "Model Tuning and Optimization:",
          "·	Hyperparameter Tuning: Grid Search, Randomized Search",
          "·	Regularization: L1, L2",
          "·	Cross-Validation Techniques",
        ],
      },
      {
        id: 9,
        title: "Natural Language Processing",
        topics: [
          "NLP Basics",
          "·	Tokenization, Stemming, and Lemmatization",
          "Text Representations",
          "·	Bag of Words, TF-IDF, Word2Vec",
          "Preprocessing Text for Machine Learning",
          "·	Removing Stopwords, Lowercasing, and Special Character Removal",
          "Project: Sentiment Analysis, Fake News Prediction, Bullying Detection Using NLP Techniques (Both english & bangla)",
        ],
      },
      {
        id: 10,
        title: "Deep Learning",
        topics: [
          "Neural Networks",
          "Artificial Neural Networks (ANN)",
          "·	Introduction to TensorFlow, Building Neural Networks",
          "·	Activation Functions, Forward and Backpropagation",
          "Convolutional Neural Networks (CNN)",
          "·	Max Pooling, Padding",
          "·	Image Classification",
          "Recurrent Neural Networks (RNN)",
          "·	Sequence Models for NLP",
          "Long Short-Term Memory (LSTM) Networks",
          "·	Sequence Models for NLP ",
          "Project: Image Classification, Stock price prediction using  Deep Learning",
        ],
      },
      {
        id: 11,
        title: "Database: Mysql",
        topics: [
          "Introduction to SQL - What Is SQL & Database",
          "Data Types, Primary-Foreign Keys & Constraints",
          "Install MySQL ",
          "Create Table In SQL & Create Database",
          "INSERT UPDATE, DELETE & ALTER Table",
          "SELECT Statement & WHERE Clause with Example",
          "How To Import Excel File (CSV) to SQL",
          "Functions in SQL & String Function",
          "Aggregate Functions – Types & Syntax",
          "Group By and Having Clause",
          "Time Stamp and Extract Function, Date Time Function",
          "SQL JOINS – Types & Syntax",
          "SELF JOIN, UNION & UNION ALL",
          "Subquery",
          "Window Function – Types & Syntax",
          "Case Statement/Expression with examples",
          "CTE - Common Table Expression with examples",
        ],
      },
      {
        id: 12,
        title: "Web Framework (Flask & Streamlit)",
        topics: [
          "Web App Development:",
          "·	Introduction to Flask: API Creation and Deployment",
          "·	Basics of HTML and CSS for Web Apps",
          "·	Database Integration",
          "Deploying Models with Streamlit",
          "Building a Web Application with Model Deployment",
        ],
      },
      {
        id: 13,
        title: "BI Tool: PowerBI",
        topics: [
          "PowerBI Basics",
          "Data Loading & Transformation",
          "Data Modeling, Basic DAX and Starting Portfolio Project 01",
          "DAX Functions & Visualization Essentials",
          "Advanced DAX & Project Visualization",
          "Interactive & Map Visualizations",
          "Advanced Report Customization",
          "Finalizing & Deploying Project 01",
          "Starting Portfolio Project 02 - Cohort & RFM Analysis",
          "Advanced DAX for Cohort & RFM Analysis",
          "Course Completion & Final Projects",
        ],
      },
      {
        id: 14,
        title: "Git & GitHub",
        topics: [
          "GitHub Workflow:",
          "·	Create a Repository",
          "·	Connect to GitHub",
          "·	Push Code",
          "·	Collaboration",
          "·	Fork",
          "·	Pull Request",
          "·	Code Review",
          "·	Issue Tracking",
        ],
      },
      {
        id: 15,
        title: "Final Project",
        topics: [
          "Students submit a capstone project and discuss their learnings and implementation",
        ],
      },
    ],
  },
  {
    id: "2",
    title: "Mastering Data Analysis",
    instructor: "Md. Asif Mredha",
    instructorDetails: [
      "Managing Director, Kryzotech",
      "Machine Learning Trainer, Hamdard University Bangladesh",
      "Former Data Scientist, Nighthawk",
      "Former Data Science Trainer, Microland IT Institute",
      'Formulated the course outline for the "Big Data, Data Analytics, and Data Science" for SEIP',
    ],
    modules: [
      {
        id: 1,
        title: "Introduction to Data Analysis",
        topics: [
          "Overview of Data Analysis",
          "Roadmap to Becoming a Data Analyst",
          "Importance of Data Analysis in Industry",
          "Real-world Applications of Data Analysis",
        ],
      },
      {
        id: 2,
        title: "Microsoft Excel",
        topics: [
          "Introduction: Statistics & Understanding Data",
          "All types of Necessary Excel Formula & Their Use",
          "Power query data consolidation & Dynamic array formulas",
          "Assignment 01",
          "Assignment 1 Solution",
          "Assignment 01 Data Analysis With Charts",
          "Statistical Analysis: Regression, Anova, 2 Sample t test, Paired t test & Descriptive Statistics",
          "Portfolio Project Dashboard Building by Superstore Data",
          "Assignment 2: Portfolio Project Building by Hotel Management Booking Data",
          "Online Projects Showcase to Others",
        ],
      },
      {
        id: 3,
        title: "Statistics",
        topics: [
          "Descriptive Statistics",
          "Probability Theory",
          "Hypothesis Testing",
          "Statistical Inference",
          "Correlation and Regression Analysis",
          "Forecasting: Time Series Analysis",
        ],
      },
      {
        id: 4,
        title: "Database: Mysql",
        topics: [
          "Introduction to SQL - What Is SQL & Database",
          "Data Types, Primary-Foreign Keys & Constraints",
          "Install MySQL",
          "Create Table In SQL & Create Database",
          "INSERT UPDATE, DELETE & ALTER Table",
          "SELECT Statement & WHERE Clause with Example",
          "How To Import Excel File (CSV) to SQL",
          "Functions in SQL & String Function",
          "Aggregate Functions – Types & Syntax",
          "Group By and Having Clause",
          "Time Stamp and Extract Function, Date Time Function",
          "SQL JOINS – Types & Syntax",
          "SELF JOIN, UNION & UNION ALL",
          "Subquery",
          "Window Function – Types & Syntax",
          "Case Statement/Expression with examples",
          "CTE - Common Table Expression with examples",
        ],
      },
      {
        id: 5,
        title: "BI Tool: PowerBI",
        topics: [
          "PowerBI Basics",
          "Data Loading & Transformation",
          "Data Modeling, Basic DAX and Starting Portfolio Project 01",
          "DAX Functions & Visualization Essentials",
          "Advanced DAX & Project Visualization",
          "Interactive & Map Visualizations",
          "Advanced Report Customization",
          "Finalizing & Deploying Project 01",
          "Starting Portfolio Project 02 - Cohort & RFM Analysis",
          "Advanced DAX for Cohort & RFM Analysis",
          "Course Completion & Final Projects",
        ],
      },
      {
        id: 6,
        title: "Programming Language (Python)",
        topics: [
          "Introduction to Python for Data Science",
          "Setup and Installation:",
          "·	Installing Python and IDEs (e.g., PyCharm, VS Code, Jupyter Notebook).",
          "Basic Syntax",
          "·	Print Function, Variables, and Input Handling",
          "Data Types and Casting",
          "·	Overview of Python Data Types",
          "·	Casting between data types",
          "Operators",
          "·	Arithmetic, Assignment, Comparison, Logical, Identify, and Membership operators",
          "Statements",
          "·	Comments, Pass, Break, Continue, and Switch-case Implementations.",
          "Problem Solving",
          "·	Writing simple Python programs to solve basic problems",
          "Python Control Flow and Data Structures",
          "Control Flow:",
          "·	If-Else Statements and Nested Loops",
          "·	For and While Loops with practical examples",
          "Data Structures",
          "·	Overview of Lists, Tuples, Dictionaries, and Arrays",
          "·	Practical use cases for each data structure",
          "Functions in Python:",
          "·	Defining Functions, Parameters, and Return Statements",
          "·	Lambda Functions and their applications.",
          "Basics of Object-Oriented Programming (OOP):",
          "·	Introduction to Classes and Objects",
          "·	Attributes and Methods",
          "·	Constructors (__init__ method)",
          "·	Inheritance ",
          "·	Encapsulation and Abstraction",
          "·	Polymorphism",
          "Exception Handling in Python:",
          "·	Try-Except Block",
          "·	Finally Block",
          "·	Raising Exceptions",
          "File Handling in Python:",
          "·	Reading Text Files",
          "·	Writing & Appending to Text Files",
          "·	Delete file & folder",
          "Project:",
          "·	Develop a small project using Python",
        ],
      },
      {
        id: 7,
        title: "Unlocking Numerical Computing using Numpy",
        topics: [
          "NumPy Basics:",
          "·	Introduction to Jupyter Notebook",
          "·	Creating and Manipulating Arrays",
          "·	Slicing, Dicing, and Reshaping Arrays",
          "Mathematical Operations:",
          "·	Basic Arithmetic, Random Value Generation",
          "·	Min/Max/Mean Functions, Joining and Splitting Arrays",
        ],
      },
      {
        id: 8,
        title: "Data Manipulation with Pandas",
        topics: [
          "Introduction to Pandas",
          "·	Importing and Exporting Datasets",
          "·	Handling Missing Data",
          "DataFrame Operations",
          "·	Dropping, Grouping, and Sorting Data",
          "·	Filtering Data, Creating New Columns",
          "Project: Exploratory Data Analysis (EDA) on a Real Dataset Using Pandas",
        ],
      },
      {
        id: 9,
        title: "Data Visualization with Matplotlib",
        topics: [
          "Basic Plotting:",
          "·	Line, Scatter, and Bar Plots",
          "·	Customizing Plots: Labels, Grids, Legends",
          "Advanced Visualizations:",
          "·	Subplots, Histograms, Pie Charts",
          "·	Plot Styles and Aesthetics",
          "Project: Visualizing Trends in Data Using Matplotlib",
        ],
      },
      {
        id: 10,
        title: "Data Visualization with Seaborn",
        topics: [
          "Introduction to Seaborn:",
          "·	Relational and Categorical Plots (Scatter, Line, Bar, Box, etc.)",
          "Distribution and Aesthetics:",
          "·	Histograms, KDE Plots, and Violin Plots",
          "·	Customizing Seaborn Colors and Plot Grids",
          "Project: Create Detailed Plots to Explore Data Patterns",
        ],
      },
      {
        id: 11,
        title: "Git & GitHub",
        topics: [
          "GitHub Workflow",
          "·	Create a Repository",
          "·	Connect to GitHub",
          "·	Push Code",
          "·	Collaboration",
          "·	Fork",
          "·	Pull Request",
          "·	Code Review",
          "·	Issue Tracking",
        ],
      },
      {
        id: 12,
        title: "Final Project",
        topics: [
          "Students submit a capstone project and discuss their learnings and implementation",
        ],
      },
    ],
  },
  {
    id: "3",
    title: "Data Analysis with Python",
    instructor: "Md. Asif Mredha",
    instructorDetails: [
      "Managing Director, Kryzotech",
      "Machine Learning Trainer, Hamdard University Bangladesh",
      "Former Data Scientist, Nighthawk",
      "Former Data Science Trainer, Microland IT Institute",
      'Formulated the course outline for the "Big Data, Data Analytics, and Data Science" for SEIP',
    ],
    modules: [
      {
        id: 1,
        title: "Introduction to Python for Data Analysis",
        topics: [
          "Setup and Installation",
          "Basic Syntax",
          "Data Types and Casting",
          "Operators",
          "Statements",
          "Problem Solving",
        ],
      },
      {
        id: 2,
        title: "Python Control Flow and Data Structures",
        topics: ["Control Flow", "Data Structures", "Functions in Python"],
      },
      {
        id: 3,
        title: "Basics of Object-Oriented Programming (OOP)",
        topics: [
          "Introduction to Classes and Objects",
          "Attributes and Methods",
          "Constructors (__init__ method)",
          "Inheritance",
          "Encapsulation and Abstraction",
          "Polymorphism",
        ],
      },
      {
        id: 4,
        title: "Exception Handling in Python",
        topics: ["Try-Except Block", "Finally Block", "Raising Exceptions"],
      },
      {
        id: 5,
        title: "File Handling in Python",
        topics: [
          "Reading Text Files",
          "Writing & Appending to Text Files",
          "Delete file & folder",
          "Project: Develop a small program using python",
        ],
      },
      {
        id: 6,
        title: "Libraries for Data Analysis",
        topics: [
          "NumPy for Numerical Computations",
          "Pandas for Data Manipulation",
          "Matplotlib for Visualization",
          "Seaborn for Statistical Visualization",
        ],
      },
      {
        id: 7,
        title: "Working with Real-World Data",
        topics: [
          "Data Cleaning and Preprocessing",
          "Exploratory Data Analysis (EDA)",
          "File Handling in Python",
        ],
      },
      {
        id: 8,
        title: "Advanced Topics in Data Analysis",
        topics: [
          "Merging and Aggregating Data",
          "Custom Visualizations",
          "Data Transformation",
        ],
      },
      {
        id: 9,
        title: "Capstone Projects",
        topics: [
          "Bitcoin Price Analysis",
          "Credit Card Default Analysis",
          "Genetic Disorder Analysis",
          "Additional Projects",
        ],
      },
    ],
  },
  {
    id: "4",
    title: "Mysql for Data Analysis",
    instructor: "Md. Asif Mredha",
    instructorDetails: [
      "Managing Director, Kryzotech",
      "Machine Learning Trainer, Hamdard University Bangladesh",
      "Former Data Scientist, Nighthawk",
      "Former Data Science Trainer, Microland IT Institute",
      'Formulated the course outline for the "Big Data, Data Analytics, and Data Science" for SEIP',
    ],
    modules: [
      {
        id: 1,
        title: "Database: Mysql",
        topics: ["Introduction to SQL - What Is SQL & Database"],
      },
      {
        id: 2,
        title: "Data Types, Primary-Foreign Keys & Constraints",
        topics: [],
      },
      {
        id: 3,
        title: "Aggregate Functions and Data Summarization",
        topics: [],
      },
      {
        id: 4,
        title: "Data Exploration and Aggregation in MySQL",
        topics: [],
      },
      {
        id: 5,
        title: "Combining Data with Joins and Set Operations in MySQL",
        topics: [],
      },
      {
        id: 6,
        title: "Advanced Querying with Subqueries and Nested Logic in MySQL",
        topics: [],
      },
      {
        id: 7,
        title: "Mastering Date and String Manipulations in MySQL",
        topics: [],
      },
      {
        id: 8,
        title: "Advanced MySQL Techniques for Scalable Analytics",
        topics: [],
      },
      {
        id: 9,
        title: "Capstone Project and Industry Best Practices",
        topics: [],
      },
    ],
  },
  {
    id: "5",
    title: "Data Mastery with PowerBi",
    instructor: "Joy Chakma",
    instructorDetails: [
      "Founder, CTO & Chief Instructor, Digital Hill Valley",
      "Software Developer, Notre Dame University Bangladesh",
      "Research Assistant, University of East London",
    ],
    modules: [
      {
        id: 1,
        title: "PowerBI Basics",
        topics: [],
      },
      {
        id: 2,
        title: "Data Loading & Transformation",
        topics: [],
      },
      {
        id: 3,
        title: "Data Modeling, Basic DAX and Starting Portfolio Project 01",
        topics: [],
      },
      {
        id: 4,
        title: "DAX Functions & Visualization Essentials",
        topics: [],
      },
      {
        id: 5,
        title: "Advanced DAX & Project Visualization",
        topics: [],
      },
      {
        id: 6,
        title: "Interactive & Map Visualizations",
        topics: [],
      },
      {
        id: 7,
        title: "Advanced Report Customization",
        topics: [],
      },
      {
        id: 8,
        title: "Finalizing & Deploying Project 01",
        topics: [],
      },
      {
        id: 9,
        title: "Starting Portfolio Project 02 - Cohort & RFM Analysis",
        topics: [],
      },
      {
        id: 10,
        title: "Advanced DAX for Cohort & RFM Analysis",
        topics: [],
      },
      {
        id: 11,
        title: "Course Completion & Final Projects",
        topics: [],
      },
    ],
  },
  {
    id: "6",
    title: "Introduction to Natural Language Processing (NLP)",
    instructor: "Md. Asif Mredha",
    instructorDetails: [
      "Managing Director, Kryzotech",
      "Machine Learning Trainer, Hamdard University Bangladesh",
      "Former Data Scientist, Nighthawk",
      "Former Data Science Trainer, Microland IT Institute",
      'Formulated the course outline for the "Big Data, Data Analytics, and Data Science" for SEIP',
    ],
    modules: [
      {
        id: 1,
        title: "Introduction to NLP",
        topics: [
          "Overview of NLP and its applications",
          "Evolution from rule-based to deep learning models",
          "Text data representation (Tokenization, TF-IDF, Word embeddings)",
        ],
      },
      {
        id: 2,
        title: "Text Preprocessing",
        topics: [
          "Text cleaning, normalization, and feature extraction",
          "Lemmatization, stopword removal, and handling special characters",
        ],
      },
      {
        id: 3,
        title: "Machine Learning in NLP",
        topics: [
          "Supervised algorithms for text classification (e.g., Naive Bayes, SVM)",
          "Unsupervised algorithms (Clustering, Topic Modeling)",
        ],
      },
      {
        id: 4,
        title: "Deep Learning for NLP",
        topics: [
          "Introduction to RNN, LSTM, GRU for sequence tasks",
          "Transformer models like BERT, GPT for advanced NLP tasks",
        ],
      },
      {
        id: 5,
        title: " Advanced NLP Applications",
        topics: [
          "Text generation, Named Entity Recognition (NER)",
          "Machine translation and Speech-to-Text/Text-to-Speech",
        ],
      },
      {
        id: 6,
        title: " NLP Tools & Projects",
        topics: [
          "Hands-on with NLP libraries (NLTK, SpaCy, HuggingFace)",
          "Projects: Sentiment analysis, text classification, chatbots, text summarization",
        ],
      },
      {
        id: 7,
        title: " Conclusion & Future Directions",
        topics: [
          "Future trends in NLP and emerging technologies",
          "Recap and Q&A",
        ],
      },
    ],
  },
];
